features:
  AdminChat: true
  TABList: true
  EntityBlocking: true
  DupeGravel: true
  Pipes: true
  FlyingPermission: true
  ColoredSigns: true
channelname: MeggaChat
channelcolor: DARK_AQUA
messagecolor: GREEN
sendercolor: WHITE
dupeblacklist:
  - 7
  - 8
  - 9
  - 10
  - 11
  - 31
  - 34
  - 36
  - 51
  - 52
  - 59
  - 63
  - 64
  - 68
  - 71
  - 90
  - 93
  - 94
  - 119