name: MeggaChat
main: co.mcme.meggachat.MeggaChatPlugin
version: 3.0
description: Comprehensive Lightweight Admin Chat Channel!
author: meggawatts
permissions:
    meggachat.channel.a:
        default: op