name: ${project.artifactId}
main: co.mcme.meggachat.MeggaChatPlugin
version: ${project.version}
description: Comprehensive Lightweight Admin Chat Channel!
author: meggawatts
commands:
    meggachat:
        description: Allows managing MeggaChat
        usage: /<command>