# channelname can be any string
channelname: MeggaChat
# channelcolor, messagecolor, and sendercolor must be a valid Bukkit ChatColor.
# ChatColors can be found here: http://jd.bukkit.org/apidocs/org/bukkit/ChatColor.html
channelcolor: DARK_AQUA
messagecolor: GREEN
sendercolor: WHITE
# The list below controls the blacklist of the dupeflint.
# Anything here cannot be duped with the dupeflint.
dupeblacklist:
  - 7
  - 8
  - 9
  - 10
  - 11
  - 31
  - 34
  - 36
  - 51
  - 52
  - 59
  - 63
  - 64
  - 68
  - 71
  - 90
  - 93
  - 94
  - 119