name: MeggaChat
main: com.meggawatts.MeggaChat.MeggaChat
version: 1.9
description: Comprehensive Lightweight Admin Chat Channel!
author: meggawatts
permissions:
  meggachat.admin:
    description: Full access to Admin Chat.
    default: op
  meggachat.smoke:
    description: Smoke with ghast tear.
    default: op
  meggachat.smoke.digfast:
    description: Receive dig speed boost from blaze rod.
    default: op
  meggachat.smoke.runfast:
    description: Receive run speed boost from blaze powder.
    default: op
  meggachat.fly:
    description: Fly you fools!
    default: op
commands:
  a:
    usage: |
            /a on 
            /a off
            /a <message>
            /a whofly
            /a ?   