name: MeggaChat
main: com.meggawatts.MeggaChat.MeggaChat
version: 1.2
description: Comprehensive Lightweight Admin Chat Channel!
authors:
  - meggawatts
permissions:
  meggachat.admin:
    description: Full access to Admin Chat.
    default: op
  meggachat.smoke:
    description: Smoke with ghast tear.
    default: op
commands:
  a:
    usage: |
            /a on 
            /a off
            /a <message>
            /a ?